import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { ElderInfo } from "@/hooks/useApi";

interface ElderDialogProps { open: boolean; onOpenChange: (open: boolean) => void; initialData?: ElderInfo; onSubmit: (data: ElderInfo) => void; isSubmitting?: boolean; }
const emptyElder: ElderInfo = { name: "", gender: 1, idCard: "", phone: "", emergencyContact: "", emergencyPhone: "", nation: "汉族", maritalStatus: 1, education: 1, address: "", community: "", medicalInsuranceType: 1, accountStatus: 1 };

export default function ElderDialog({ open, onOpenChange, initialData, onSubmit, isSubmitting }: ElderDialogProps) {
  const [form, setForm] = useState<ElderInfo>(emptyElder);
  const [errors, setErrors] = useState<Record<string, string>>({});
  useEffect(() => { if (open) { setForm(initialData ? { ...emptyElder, ...initialData } : emptyElder); setErrors({}); } }, [open, initialData]);
  const update = (field: keyof ElderInfo, value: string | number) => { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: "" })); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const next: Record<string, string> = {}; if (!form.name.trim()) next.name = "姓名不能为空"; if (!/^[0-9Xx]{15,18}$/.test(form.idCard)) next.idCard = "身份证号格式不正确"; if (!/^1\d{10}$/.test(form.phone)) next.phone = "手机号格式不正确"; if (form.emergencyPhone && !/^1\d{10}$/.test(form.emergencyPhone)) next.emergencyPhone = "紧急联系电话格式不正确"; setErrors(next); if (Object.keys(next).length === 0) onSubmit(form); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto rounded-2xl bg-white/95 p-0"><div className="sticky top-0 z-10 border-b border-border/40 bg-white/85 px-6 py-4"><DialogHeader><DialogTitle>{initialData?.id ? "编辑老人档案" : "新增老人档案"}</DialogTitle></DialogHeader></div><form onSubmit={submit} className="grid grid-cols-1 gap-4 p-6 md:grid-cols-2">
    <div className="space-y-2"><Label>姓名 *</Label><Input value={form.name} onChange={(event) => update("name", event.target.value)} />{errors.name && <p className="text-xs text-red-600">{errors.name}</p>}</div><div className="space-y-2"><Label>性别 *</Label><select value={form.gender} onChange={(event) => update("gender", Number(event.target.value))} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="1">男</option><option value="2">女</option></select></div>
    <div className="space-y-2"><Label>出生日期</Label><Input type="date" value={form.birthDate || ""} onChange={(event) => update("birthDate", event.target.value)} /></div><div className="space-y-2"><Label>身份证号 *</Label><Input value={form.idCard} onChange={(event) => update("idCard", event.target.value)} />{errors.idCard && <p className="text-xs text-red-600">{errors.idCard}</p>}</div>
    <div className="space-y-2"><Label>联系电话 *</Label><Input value={form.phone} onChange={(event) => update("phone", event.target.value)} />{errors.phone && <p className="text-xs text-red-600">{errors.phone}</p>}</div><div className="space-y-2"><Label>民族</Label><Input value={form.nation || ""} onChange={(event) => update("nation", event.target.value)} /></div>
    <div className="space-y-2"><Label>紧急联系人</Label><Input value={form.emergencyContact || ""} onChange={(event) => update("emergencyContact", event.target.value)} /></div><div className="space-y-2"><Label>紧急联系电话</Label><Input value={form.emergencyPhone || ""} onChange={(event) => update("emergencyPhone", event.target.value)} />{errors.emergencyPhone && <p className="text-xs text-red-600">{errors.emergencyPhone}</p>}</div>
    <div className="space-y-2"><Label>婚姻状况</Label><select value={form.maritalStatus || 1} onChange={(event) => update("maritalStatus", Number(event.target.value))} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="1">未婚</option><option value="2">已婚</option><option value="3">丧偶</option><option value="4">离异</option></select></div><div className="space-y-2"><Label>文化程度</Label><select value={form.education || 1} onChange={(event) => update("education", Number(event.target.value))} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="1">小学及以下</option><option value="2">初中</option><option value="3">高中/中专</option><option value="4">大专及以上</option></select></div>
    <div className="space-y-2"><Label>医保类型</Label><select value={form.medicalInsuranceType || 1} onChange={(event) => update("medicalInsuranceType", Number(event.target.value))} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="1">城镇职工</option><option value="2">城乡居民</option><option value="3">自费</option><option value="4">其他</option></select></div><div className="space-y-2"><Label>责任医生ID</Label><Input type="number" value={form.doctorId || ""} onChange={(event) => update("doctorId", Number(event.target.value))} /></div>
    <div className="space-y-2"><Label>所属社区</Label><Input value={form.community || ""} onChange={(event) => update("community", event.target.value)} /></div><div className="space-y-2"><Label>账号状态</Label><select value={form.accountStatus ?? 1} onChange={(event) => update("accountStatus", Number(event.target.value))} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="1">正常</option><option value="0">停用</option></select></div>
    <div className="space-y-2 md:col-span-2"><Label>居住地址</Label><Input value={form.address || ""} onChange={(event) => update("address", event.target.value)} /></div><div className="flex justify-end gap-3 md:col-span-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>取消</Button><Button type="submit" disabled={isSubmitting} className="bg-gradient-to-r from-medical-400 to-medical-600 text-white">{isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}保存</Button></div>
  </form></DialogContent></Dialog>;
}
